/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessoiresRouteImport } from './routes/accessoires'
import { Route as CasquesRouteImport } from './routes/casques'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EquipementsRouteImport } from './routes/equipements'
import { Route as MotosRouteImport } from './routes/motos'
import { Route as PiecesRouteImport } from './routes/pieces'
import { Route as RevendeursRouteImport } from './routes/revendeurs'
import { Route as ProduitsSlugRouteImport } from './routes/produits.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoiresRoute = AccessoiresRouteImport.update({
  id: '/accessoires',
  path: '/accessoires',
  getParentRoute: () => rootRouteImport,
} as any)
const CasquesRoute = CasquesRouteImport.update({
  id: '/casques',
  path: '/casques',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipementsRoute = EquipementsRouteImport.update({
  id: '/equipements',
  path: '/equipements',
  getParentRoute: () => rootRouteImport,
} as any)
const MotosRoute = MotosRouteImport.update({
  id: '/motos',
  path: '/motos',
  getParentRoute: () => rootRouteImport,
} as any)
const PiecesRoute = PiecesRouteImport.update({
  id: '/pieces',
  path: '/pieces',
  getParentRoute: () => rootRouteImport,
} as any)
const RevendeursRoute = RevendeursRouteImport.update({
  id: '/revendeurs',
  path: '/revendeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsSlugRoute = ProduitsSlugRouteImport.update({
  id: '/produits/$slug',
  path: '/produits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessoires': typeof AccessoiresRoute
  '/casques': typeof CasquesRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/motos': typeof MotosRoute
  '/pieces': typeof PiecesRoute
  '/revendeurs': typeof RevendeursRoute
  '/produits/$slug': typeof ProduitsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessoires': typeof AccessoiresRoute
  '/casques': typeof CasquesRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/motos': typeof MotosRoute
  '/pieces': typeof PiecesRoute
  '/revendeurs': typeof RevendeursRoute
  '/produits/$slug': typeof ProduitsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessoires': typeof AccessoiresRoute
  '/casques': typeof CasquesRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/motos': typeof MotosRoute
  '/pieces': typeof PiecesRoute
  '/revendeurs': typeof RevendeursRoute
  '/produits/$slug': typeof ProduitsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessoires'
    | '/casques'
    | '/catalogue'
    | '/contact'
    | '/equipements'
    | '/motos'
    | '/pieces'
    | '/revendeurs'
    | '/produits/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessoires'
    | '/casques'
    | '/catalogue'
    | '/contact'
    | '/equipements'
    | '/motos'
    | '/pieces'
    | '/revendeurs'
    | '/produits/$slug'
  id:
    | '__root__'
    | '/'
    | '/accessoires'
    | '/casques'
    | '/catalogue'
    | '/contact'
    | '/equipements'
    | '/motos'
    | '/pieces'
    | '/revendeurs'
    | '/produits/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoiresRoute: typeof AccessoiresRoute
  CasquesRoute: typeof CasquesRoute
  CatalogueRoute: typeof CatalogueRoute
  ContactRoute: typeof ContactRoute
  EquipementsRoute: typeof EquipementsRoute
  MotosRoute: typeof MotosRoute
  PiecesRoute: typeof PiecesRoute
  RevendeursRoute: typeof RevendeursRoute
  ProduitsSlugRoute: typeof ProduitsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessoires': {
      id: '/accessoires'
      path: '/accessoires'
      fullPath: '/accessoires'
      preLoaderRoute: typeof AccessoiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casques': {
      id: '/casques'
      path: '/casques'
      fullPath: '/casques'
      preLoaderRoute: typeof CasquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipements': {
      id: '/equipements'
      path: '/equipements'
      fullPath: '/equipements'
      preLoaderRoute: typeof EquipementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motos': {
      id: '/motos'
      path: '/motos'
      fullPath: '/motos'
      preLoaderRoute: typeof MotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pieces': {
      id: '/pieces'
      path: '/pieces'
      fullPath: '/pieces'
      preLoaderRoute: typeof PiecesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revendeurs': {
      id: '/revendeurs'
      path: '/revendeurs'
      fullPath: '/revendeurs'
      preLoaderRoute: typeof RevendeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/$slug': {
      id: '/produits/$slug'
      path: '/produits/$slug'
      fullPath: '/produits/$slug'
      preLoaderRoute: typeof ProduitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoiresRoute: AccessoiresRoute,
  CasquesRoute: CasquesRoute,
  CatalogueRoute: CatalogueRoute,
  ContactRoute: ContactRoute,
  EquipementsRoute: EquipementsRoute,
  MotosRoute: MotosRoute,
  PiecesRoute: PiecesRoute,
  RevendeursRoute: RevendeursRoute,
  ProduitsSlugRoute: ProduitsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
